server:
  address: localhost
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬 테스트용 DB
    url: jdbc:mysql://localhost:3306/fieldgeolog?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      springframework:
        web: DEBUG